### ISSUE TITLE
Inconsistency in test case

### ISSUE THREAD

**Issue by arjan** [speechmarkdown/speechmarkdown-test-files#3]
I found an inconsistency in [this test](https://github.com/speechmarkdown/speechmarkdown-test-files/blob/master/test-data/break-strength/break-strength.smd)

Is `[break:none]` expected to be valid syntax? e.g. an attribute value without quotes?

**Comment by rmtuckerphx** [comment]
Values should have single or double quotes

**Comment by arjan** [comment]
Added PR #4 which addresses this
